-- 					~ FINAL PROJECT ~

USE SOCIAL_MEDIA ; 

-- 1. DISPLAY TABLE LOGIN, USERS, POST.

SELECT * FROM LOGIN ; 
SELECT * FROM USERS ; 
SELECT * FROM POST ; 

-- 2. OPEN ER DISGRAM.

-- 3. FIND USERS FROM MAHARASHTRA. [9]
SELECT * FROM POST ; 
SELECT USER_ID, LOCATION FROM POST WHERE LOCATION = 'MAHARASHTRA' ; 

-- 4.  FIND USERS WITH THEIR NAMES FROM MAHARASHTRA. [9]

-- SUBQUERY 

SELECT * FROM USERS WHERE USER_ID IN
(SELECT USER_ID FROM POST WHERE LOCATION = 'MAHARASHTRA') ; 

-- ALSO TRY WITH JOIN.

-- 5. DISPLAY USERS WITH LONGEST CAPTIONS. 
SELECT * FROM POST ; 
SELECT USER_ID, CAPTION, length(CAPTION) FROM POST ORDER BY 3 DESC LIMIT 5; 

-- 6. AVERAGE POSTS PER USER.
SELECT * FROM POST ; 
SELECT COUNT(POST_ID) / COUNT(DISTINCT USER_ID) AS 'AVERAGE POSTS PER USER'
FROM POST ;

-- 7. DISPLAY USERS WITH NO (0) COMMENTS. [1]
SELECT * FROM USERS ; 
SELECT * FROM COMMENTS ; 

-- SUBQUERY
SELECT USER_ID, USERNAME FROM USERS WHERE USER_ID NOT IN
(SELECT DISTINCT USER_ID FROM COMMENTS );

-- 8. DISPLAY NO OF LOGINS PER USER.   [JOINS]
SELECT * FROM USERS ; 
SELECT * FROM LOGIN ; 

SELECT COUNT(DISTINCT T1.USER_ID)/ COUNT(DISTINCT T2.LOGIN_ID)  AS 'AVG LOGIN'
FROM USERS T1 LEFT OUTER JOIN 
LOGIN T2 ON T1.user_id = T2.USER_ID ; 

-- 9. DISPLAY USERS NOT FOLLOWED BY ANYONE.  [0]

SELECT * FROM USERS ;
SELECT * FROM FOLLOWS ; 

SELECT USER_ID, USERNAME FROM USERS WHERE USER_ID NOT IN 
(SELECT DISTINCT followee_id FROM FOLLOWS) ; 

-- 10. DISPLAY USERS WITH POST GREATER THAN OR EQUALS TO 5.

SELECT * FROM USERS  ;
SELECT * FROM POST ; 

SELECT T2.USER_ID, T1.USERNAME, COUNT(*) FROM USERS T1 INNER JOIN POST T2
ON T1.USER_ID = T2.USER_ID GROUP BY 1 HAVING COUNT(*) >= 4 ORDER BY 3 DESC; 

-- 11. DISPLAY USER ID, USERNAME WITH GREATER THAN OR EQUALS TO 3 COMMENTS.
SELECT * FROM USERS  ;
SELECT * FROM COMMENTS ; 

SELECT T2.USER_ID, T1.USERNAME, COUNT(*) FROM USERS T1 INNER JOIN COMMENTS T2
ON T1.USER_ID = T2.USER_ID GROUP BY 1 HAVING COUNT(*) >= 3 ORDER BY 3 DESC; 

-- ---------------------------------------------------------------------------


-- EXERCISE : 
-- 1. DISPLAY NO OF COMMENTS BY EACH USERS.
-- 2. DISPLAY NO OF PHOTOS POSTED BY EACH USER.
-- 3. DISPLAY VIDEOS POSTED BY EACH USER.
-- 4. DISPLAY MOST LIKED POSTS. 
-- 5. DISPLAY MOST USED HASHTAGS. 





