  
  
-- 					~  MID TERM PROJECT ~ 

-- OLTP / OLAP 

-- 1. DISPLAY TABLE.
SELECT * FROM CALL_DATA ; 

-- 2. IDENTIFY CATEGORICAL FEATURES. 

SELECT DISTINCT SENTIMENT FROM CALL_DATA ;  -- [5]
SELECT DISTINCT CSAT_SCORE FROM CALL_DATA ;  -- [10/11]
SELECT DISTINCT REASON FROM CALL_DATA ;      -- [3]
SELECT DISTINCT CITY FROM CALL_DATA ;        -- [457]
SELECT DISTINCT STATE FROM CALL_DATA ;       -- [51]
SELECT DISTINCT CHANNEL FROM CALL_DATA ;     -- [4]
SELECT DISTINCT RESPONSE_TIME FROM CALL_DATA ;  -- [3]
SELECT DISTINCT CALL_CENTER FROM CALL_DATA ;    -- [4]

--  ~ DQL ~
-- 1. COLUMN SELECTION
-- 2. COLUMN OPERATIONS
-- 3. CONDITIONS 
-- 4. GROUP BY, ORDER BY 

-- 1. IDENTIFY SHAPE OF THE DATA
-- COLUMNS = 12 ,   ROWS = 9611
SELECT COUNT(*) FROM CALL_DATA ; 

-- 2. DISPLAY MIN, MAX, AVG DURATION OF THE CALL.

SELECT MIN(call_duration_minutes) AS 'MIN DURATION CALL' , 
MAX(call_duration_minutes) AS 'MAX DURATION CALL',
ROUND(AVG(call_duration_minutes), 1) AS 'AVG DURATION OF CALL'
FROM CALL_DATA ; 

-- 3. DISPLAY TOTAL CALLS FOR EACH REASON. 
SELECT REASON, COUNT(*) FROM call_data GROUP BY 1 ; 

-- 4. DISPLAY SENTIMENT CALL COUNT.
SELECT SENTIMENT , COUNT(*) FROM call_data GROUP BY 1 ORDER BY 2 DESC; 

-- 5. DISPLAY 5 CITIES WITH MAX COMPLAINTS.
 SELECT CITY , COUNT(*) FROM CALL_DATA GROUP BY 1 ORDER BY 2 DESC LIMIT 5  ; 

-- 6. DISPLAY 5 STATES  WITH MIN COMPLAINTS. 
SELECT STATE , COUNT(*) FROM CALL_DATA GROUP BY 1 ORDER BY 2 LIMIT 5 ; 

-- 7. DISPLAY CHANNEL WISE TOTAL ENGAGEMENT, AVERAGE ENGAGEMENT.
SELECT CHANNEL, sum(call_duration_minutes) AS ENGAGEMENT, 
ROUND(avg(call_duration_minutes),1) AS 'AVERAGE ENGAGEMENT'
 FROM CALL_DATA
GROUP BY 1 ; 


-- 8. GIVE SENTIMENT WISE AVERAGE CALL DURATION.
SELECT SENTIMENT, ROUND(AVG(call_duration_minutes), 1) FROM CALL_DATA
GROUP BY 1  ; 


-- 9. GIVE CHANNEL WISE AVEGARE CUSTOMER SATISFACTION.
SELECT CHANNEL, ROUND(AVG(csat_score),1) FROM CALL_DATA 
WHERE csat_score > 0  GROUP BY 1 ; 

-- 10. GIVE CALL_CENTER WISE AVEGARE CUSTOMER SATISFACTION.
-- 11. GIVE CALL_CENTER WISE AVEGARE ENGAGEMENT. 
-- -----------------------------------------------------------------------------

 -- 10. GIVE REASON WISE SENTIMENT COUNT.
 
 SELECT REASON, SENTIMENT, COUNT(*) FROM CALL_DATA 
 GROUP BY 1, 2  ORDER BY 2 , 3 DESC; 
 
 -- 11. IDENTIFY TOP 5 STATES WITH COMPLAINTS AND ALSO FIND THEIR PERCENTAGES.

SELECT STATE , COUNT(*) ,
ROUND(COUNT(*) / (SELECT COUNT(*) FROM CALL_DATA) * 100, 1)  AS '% COMPLAINTS'
FROM CALL_DATA GROUP BY 1 ORDER BY 2 DESC LIMIT 5 ;  
 
-- 12. GIVE TOP 5 CITIES WITH COMPLAINTS FROM SATATE CALIFORNIA. 
SELECT CITY , COUNT(*) FROM CALL_DATA WHERE STATE = 'CALIFORNIA' 
GROUP BY 1 ORDER BY 2 DESC LIMIT 5;

 


